language: java

jdk:
 - openjdk14

sudo: false

script:
 - mvn test -B

env:
 global:
  - CODECOV_TOKEN="de1d338f-f325-4c78-ad5e-2361a8d16df2"

after_success:
 - bash <(curl -s https://codecov.io/bash)


notifications:
 email:
  recipients:
   -d.kirenkov@gmail.com
  on_success: never # default: change
  on_failure: always # default: always